"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const obs = require('./distribute/obs_node.node');
const path = require("path");
exports.DefaultD3D11Path = path.resolve(__dirname, `distribute/libobs-d3d11.dll`);
exports.DefaultDrawPluginPath = path.resolve(__dirname, `distribute/simple_draw.dll`);
exports.DefaultBinPath = path.resolve(__dirname, `distribute`);
exports.DefaultDataPath = path.resolve(__dirname, `distribute/data`);
exports.DefaultPluginPath = path.resolve(__dirname, `distribute/obs-plugins`);
exports.DefaultPluginDataPath = path.resolve(__dirname, `distribute/data/obs-plugins/%module%/data`);
exports.Global = obs.Global;
exports.InputFactory = obs.Input;
exports.SceneFactory = obs.Scene;
exports.FilterFactory = obs.Filter;
exports.TransitionFactory = obs.Transition;
exports.DisplayFactory = obs.Display;
exports.VolmeterFactory = obs.Volmeter;
exports.FaderFactory = obs.Fader;
exports.Video = obs.Video;
exports.ModuleFactory = obs.Module;
