
mkdir ${SLBUILDDIRECTORY}
cd ${SLBUILDDIRECTORY}
mkdir ${SLDISTRIBUTEDIRECTORY}
cd ${SLDISTRIBUTEDIRECTORY}
mkdir obs-studio-node
cd ..

cmake .. \
-DCMAKE_INSTALL_PREFIX=$PWD/${SLDISTRIBUTEDIRECTORY}/obs-studio-node \
-DSTREAMLABS_BUILD=OFF \
-DNODEJS_NAME=${RUNTIMENAME} \
-DNODEJS_URL=${RUNTIMEURL} \
-DNODEJS_VERSION=v${ELECTRONVERSION} \
-DLIBOBS_BUILD_TYPE=${RELEASENAME} \
-DCMAKE_BUILD_TYPE=${BUILDCONFIG}

cd ..