
mkdir ${SLBUILDDIRECTORY}

cd ${SLBUILDDIRECTORY}

cmake .. \
-DCMAKE_INSTALL_PREFIX=${SLFULLDISTRIBUTEPATH}\obs-studio-node \
-DSTREAMLABS_BUILD=OFF \
-DNODEJS_NAME=${RUNTIMENAME} \
-DNODEJS_URL=${RUNTIMEURL} \
-DNODEJS_VERSION=${ELECTRONVERSION} \
-DLIBOBS_BUILD_TYPE=${RELEASENAME} \
-DCMAKE_BUILD_TYPE=${BUILDCONFIG}

cd ..